# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0acd585358eede93ff175f0194be10fe586fd2e33cf0fe9810691a117e226566fc051a80edd2bf6dea3aad2cb1e86ca3c48e56f8cb0d9565f634f0a12959f1f5

test:
  secret_key_base: 0249c2e318e5f05c13234e61c2ccfdd82c4a7fa31e947db705d093f248c231cb57ffefbf1442cbc908c0561db36d232462a56df2d47bd25b0052c3135ba2806c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
