# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 397123f8a35102521ce2339becd98659b69db01caaa3b2183c195b925ef99b0d72d2d5889af21cfe8f65a70d21cf9d0ca239e8287f44c6e42aa8373eacb04d30

test:
  secret_key_base: e2b3dc1a8639391381fcb2c75ef85effcab31f300adca1a84390ecd892469359ffd1969ac082c671349bd8c31dcf8443e2f16cecace353702555ee6a0d3198ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
